[toolchain]
	anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
minting = "7VNYAn8xGrybRLic4i6vUzmbsKhHFrnZq5cAzSMoP5PL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "http://127.0.0.1:8899"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "tests/metaplex_token_metadata_program.so"
